# Start with a base image containing runtime
FROM nginx:1.24.0
# Custom Param
ARG fileName
ENV fileName=${fileName}
ARG filePath
ENV filePath=${filePath}
RUN echo "Custom Param：fileName=${fileName}，filePath=${filePath}"

# Add the built artifact
ADD ${filePath}/${fileName} /usr/share/nginx/html/
WORKDIR /usr/share/nginx/html/

COPY nginx/default.conf /etc/nginx/conf.d/default.conf